# Generated by Django 3.1.4 on 2020-12-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
