# Generated by Django 3.1.4 on 2021-01-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
    ]
