# Generated by Django 3.1.4 on 2021-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20210111_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
