# Generated by Django 3.1.4 on 2021-01-11 21:08

from django.db import migrations

from channels.yt_api import get_video_title


def fetch_title(apps, schema_editor):
    # We can't import the Video model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Video = apps.get_model("channels", "Video")
    for video in Video.objects.all():
        video.title = get_video_title(video.url[-11:])
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0005_video_title"),
    ]

    operations = [
        migrations.RunPython(fetch_title),
    ]
