# Generated by Django 3.1.4 on 2021-01-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20210112_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='yt_channel',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.ytchannel'),
            preserve_default=False,
        ),
    ]
