# Generated by Django 3.1.4 on 2021-01-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_auto_20210112_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('tags', models.ManyToManyField(to='channels.Tag')),
                ('yt_channel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='channels.ytchannel')),
            ],
        ),
    ]
