# Generated by Django 3.1.4 on 2021-01-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='number_of_videos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
