# Generated by Django 3.1.4 on 2021-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0013_auto_20210114_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
