# Generated by Django 3.1.4 on 2021-01-19 12:53

from django.db import migrations


def populate_channel_titles(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")

    for channel in Channel.objects.all():
        channel.title = ", ".join([t.name for t in channel.tags.all()])
        channel.save()


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0014_channel_title"),
    ]

    operations = [
        migrations.RunPython(populate_channel_titles),
    ]
